# 🧮 MathAI — Gerenciador de Questões (Caderno Interativo)

cadastrar, testar e visualizar questões no banco de dados célula a célula.

In [1]:
import sys
from pathlib import Path
import json
from datasets import load_dataset

# Adiciona a raiz do projeto no sys.path para importar o pacote 'src'
ROOT_DIR = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()
if str(ROOT_DIR) not in sys.path:
    sys.path.append(str(ROOT_DIR))

from src.database.db import (
    pegar_conexao, 
    inserir_questao, 
    listar_questoes, 
    limpar_questoes, 
    buscar_questao_por_id,
    excluir_questao
)
from IPython.display import display, Markdown, SVG

print('✅ Módulos do MathAI importados com sucesso!')

✅ Módulos do MathAI importados com sucesso!

## 🧹 (Opcional) Limpar Tabela e Resetar IDs
zerar as questões anteriores e recomeçar os IDs a partir do 1, descomente e execute a célula abaixo:

In [ ]:
#limpar_questoes()
#excluir_questao()

Tabela 'questoes' limpa e ID resetado com sucesso!

## 📋 Consultar Todas as Questões no Banco
Veja todas as questões que já estão salvas no banco `data/mathai.db`:

In [2]:
questoes = listar_questoes()
print(f"Total de questões cadastradas no banco: {len(questoes)}\n")

#for q in questoes:
    #display(Markdown(f"### Questão {q['id']:02d} — {q['materia']} | *{q['topico']}* ({q['banca']} {q['ano']})"))
    #display(Markdown(q['enunciado']))
    #if q['figura_path']:
        #fig_path = Path("..") / q['figura_path']
        #if fig_path.exists():
            #display(SVG(filename=str(fig_path)))
    #display(Markdown(f"**Gabarito Oficial:** `{q['gabarito']}` | **Estratégias:** `{q['estrategias_esperadas']}`"))
    #display(Markdown("---"))

Total de questões cadastradas no banco: 248

## ➕ Cadastrar Nova Questão Avulsa (Template)
Use o template abaixo quando quiser cadastrar uma nova questão individual no banco:

In [ ]:
enunciado_novo = r"""Escreva aqui o enunciado com fórmulas em LaTeX $x^2$."""

id_novo = inserir_questao(
    materia="Álgebra",
    topico="Exemplo",
    subtopico=None,
    dificuldade=None,
    banca="ESA",
    ano=2026,
    enunciado=enunciado_novo,
    gabarito="A",
    figura_path=None,
    estrategias_esperadas=["Estratégia 1", "Estratégia 2"]
)
print(f"Questão cadastrada com ID: {id_novo}")

## 🎖️ Prova Oficial ESA 2026 — Todas as 12 Questões
A célula abaixo contém todas as 12 questões da prova da ESA 2026 estruturadas com $\LaTeX$, gabaritos, estratégias cognitivas e figuras vetoriais. Execute a célula (`Shift + Enter`) para inserir todas de uma vez:

In [102]:
questoes_esa_2026 = [
    # Questão 01
    {
        "materia": "Álgebra",
        "topico": "Funções",
        "subtopico": "Função Afim e Quadrática",
        "dificuldade": None,
        "banca": "ESA",
        "ano": 2026,
        "enunciado": r"""A robótica tem se tornado cada vez mais presente nas Forças Armadas. Robôs são desenvolvidos e empregados para aumentar a segurança dos combatentes e executar tarefas em que são guiados por meio de controle remoto. Durante um exercício no Campo de Instrução da Escola de Sargentos das Armas, um robô, que se encontra na origem de um sistema cartesiano ortogonal, deve passar pelos pontos $A(1,1)$, $B(2,0)$ e $C(4,4)$, que também estão no mesmo plano cartesiano. Inicialmente, ele deve caminhar em linha reta até o ponto $A$. Em seguida, deve ajustar sua trajetória para deslocar-se sobre um arco parabólico, a fim de passar pelos pontos $B$ e $C$. Dessa forma, o robô deve ser programado para deslocar-se sobre o gráfico da função:

$$
f(x) = \begin{cases}
mx, & \text{se } 0 \le x \le 1 \\\\
ax^2 + bx + c, & \text{se } x > 1
\end{cases}
$$

Nesse caso, $a^2 + b^2 + c^2 + m^2$ é igual a:

(A) 32  
(B) 34  
(C) 36  
(D) 38  
(E) 40""",
        "gabarito": "B",
        "figura_path": None,
        "estrategias_esperadas": [
            "Reta passando pela Origem",
            "Sistema Linear para Coeficientes da Parábola",
            "Forma Fatorada da Quadrática"
        ]
    },

    # Questão 02
    {
        "materia": "Álgebra",
        "topico": "Função Logarítmica",
        "subtopico": "Propriedades do Gráfico e Área de Trapézio",
        "dificuldade": None,
        "banca": "ESA",
        "ano": 2026,
        "enunciado": r"""A figura abaixo representa o gráfico da função $f: \mathbb{R}_+^* \to \mathbb{R}$ definida por $f(x) = \log_2 x$. A área da região sombreada é numericamente igual a:

(A) 10  
(B) 12  
(C) 16  
(D) 18  
(E) 20""",
        "gabarito": "B",
        "figura_path": "data/uploads/esa_2026_q02.svg",
        "estrategias_esperadas": [
            "Definição de Logaritmo nos Pontos Notáveis",
            "Área do Trapézio Retângulo",
            "Interpretação Geométrica da Secante"
        ]
    },

    # Questão 03
    {
        "materia": "Análise Combinatória",
        "topico": "Combinações com Repetição",
        "subtopico": "Soluções Inteiras de Equações Lineares (Barras e Estrelas)",
        "dificuldade": None,
        "banca": "ESA",
        "ano": 2026,
        "enunciado": r"""A Escola de Sargentos das Armas (ESA) oferece as qualificações militares nas armas de Infantaria, Cavalaria, Artilharia, Engenharia e Comunicações. O fuzil, o carro de combate, o obuseiro, as máquinas de engenharia e os rádios são objetos que caracterizam essas armas, respectivamente. A fim de divulgar o Exército Brasileiro, a ESA montará uma exposição com pelo menos um objeto de cada arma, num total de 12 objetos. Se a ESA possui objetos em número suficiente e os objetos de cada arma são idênticos, de quantas maneiras diferentes a exposição poderá ser montada se ela será em linha e obedecendo ao espaço reservado, conforme esquema abaixo?

| Infantaria | Artilharia | Cavalaria | Engenharia | Comunicações |

(A) 165  
(B) 215  
(C) 330  
(D) 495  
(E) 615""",
        "gabarito": "C",
        "figura_path": None,
        "estrategias_esperadas": [
            "Método dos Traços e Pontos (Barras e Estrelas)",
            "Mudança de Variável para Soluções Positivas",
            "Combinação Simples"
        ]
    },

    # Questão 04
    {
        "materia": "Geometria Plana",
        "topico": "Relações Métricas e Cevianas",
        "subtopico": "Teorema de Menelaus",
        "dificuldade": None,
        "banca": "ESA",
        "ano": 2026,
        "enunciado": r"""Em um triângulo equilátero ($\Delta DEF$) de perímetro igual a $60\text{ cm}$, traça-se um segmento de reta com origem no ponto médio do lado $\overline{DE}$ até o ponto $R$, que se encontra sobre o prolongamento do segmento $\overline{EF}$, sendo que: $\overline{FR} = 15\text{ cm}$. Assim, o valor correto da medida de $F$ até o ponto de interseção com o lado $\overline{DF}$ é:

(A) 30 cm  
(B) 24 cm  
(C) 15 cm  
(D) 8 cm  
(E) 6 cm""",
        "gabarito": "E",
        "figura_path": None,
        "estrategias_esperadas": [
            "Teorema de Menelaus",
            "Semelhança de Triângulos com Reta Auxiliar",
            "Geometria Analítica de Coordenadas"
        ]
    },

    # Questão 05
    {
        "materia": "Teoria dos Conjuntos",
        "topico": "Conjuntos e Probabilidade",
        "subtopico": "Princípio da Inclusão-Exclusão e Diagrama de Venn",
        "dificuldade": None,
        "banca": "ESA",
        "ano": 2026,
        "enunciado": r"""Visando à preparação para a MAREXAER, competição esportiva entre as três escolas de formação de sargentos da Marinha do Brasil, do Exército Brasileiro e da Força Aérea Brasileira, um número $x$ de alunos da ESA foi selecionado para participar de uma pesquisa, visando verificar a preferência deles para três modalidades esportivas. Os resultados foram tabelados abaixo:

| Modalidade | Quantidade de alunos |
| :--- | :--- |
| Basquete | 28 |
| Futebol | 48 |
| Vôlei | 32 |
| Basquete e Futebol | 16 |
| Basquete e Vôlei | 14 |
| Futebol e Vôlei | 20 |
| Basquete, Futebol e Vôlei | 6 |

A probabilidade de se escolher um aluno que tenha preferência por, no máximo, uma modalidade analisada, entre os $x$ alunos selecionados inicialmente para a pesquisa, é igual a $\frac{21}{40}$. Nessas condições, o número de alunos entre os $x$ selecionados inicialmente que não manifestaram interesse por qualquer das modalidades analisadas é:

(A) 12  
(B) 16  
(C) 24  
(D) 32  
(E) 40""",
        "gabarito": "B",
        "figura_path": None,
        "estrategias_esperadas": [
            "Diagrama de Venn para 3 Conjuntos",
            "Princípio da Inclusão-Exclusão",
            "Definição Clássica de Probabilidade"
        ]
    },

    # Questão 06
    {
        "materia": "Estatística",
        "topico": "Medidas de Tendência Central",
        "subtopico": "Média Ponderada, Moda e Mediana",
        "dificuldade": None,
        "banca": "ESA",
        "ano": 2026,
        "enunciado": r"""Um professor de Matemática aplicou uma prova contendo 5 questões, valendo 1 ponto cada uma, a 25 alunos de uma sala. Após fazer a correção, o professor construiu o gráfico abaixo, que relaciona o número de alunos às notas obtidas por eles:

Analisando o gráfico, conclui-se que a soma da média, da moda e da mediana das notas obtidas pelos alunos é igual a:

(A) 9,15  
(B) 9,96  
(C) 8,35  
(D) 8,15  
(E) 8,59""",
        "gabarito": "B",
        "figura_path": "data/uploads/esa_2026_q06.svg",
        "estrategias_esperadas": [
            "Média Ponderada a partir de Gráfico de Colunas",
            "Identificação de Moda por Frequência Máxima",
            "Cálculo da Mediana com Número Ímpar de Elementos"
        ]
    },

    # Questão 07
    {
        "materia": "Álgebra",
        "topico": "Polinômios",
        "subtopico": "Relações de Girard e Raízes",
        "dificuldade": None,
        "banca": "ESA",
        "ano": 2026,
        "enunciado": r"""As raízes do polinômio $p(x) = 2x^3 - mx^2 + 17x - 6$ são $a$, $b$ e $2$, com $a > b$. Nesse caso, é correto afirmar que $a^b$ é igual a:

(A) 1  
(B) $\sqrt{2}$  
(C) 2  
(D) $\sqrt{3}$  
(E) 4""",
        "gabarito": "D",
        "figura_path": None,
        "estrategias_esperadas": [
            "Relações de Girard (Soma e Produto)",
            "Dispositivo Prático de Briot-Ruffini",
            "Propriedades de Potenciação e Radiciação"
        ]
    },

    # Questão 08
    {
        "materia": "Geometria Espacial",
        "topico": "Cilindros e Esferas",
        "subtopico": "Volume Deslocado e Progressão Geométrica",
        "dificuldade": None,
        "banca": "ESA",
        "ano": 2026,
        "enunciado": r"""Um cilindro, cujo raio da base mede $20\text{ cm}$, possui água em seu interior até a altura de $10\text{ cm}$. Três esferas metálicas ($E_1, E_2$ e $E_3$, nessa ordem) possuem os raios com medidas que seguem uma progressão geométrica. O raio da esfera $E_1$ mede $3\text{ cm}$. Quando essas esferas são colocadas no interior do cilindro, o nível da água sobe $6{,}57\text{ cm}$. Assim, pode-se afirmar que o volume da esfera $E_2$ é igual a:

(A) $36\pi\text{ cm}^3$  
(B) $72\pi\text{ cm}^3$  
(C) $180\pi\text{ cm}^3$  
(D) $240\pi\text{ cm}^3$  
(E) $288\pi\text{ cm}^3$""",
        "gabarito": "E",
        "figura_path": None,
        "estrategias_esperadas": [
            "Princípio de Arquimedes (Volume Deslocado no Cilindro)",
            "Fórmula do Volume da Esfera",
            "Propriedades de Progressão Geométrica"
        ]
    },

    # Questão 09
    {
        "materia": "Trigonometria",
        "topico": "Área de Triângulos",
        "subtopico": "Lei dos Senos e Fórmula Trigonométrica da Área",
        "dificuldade": None,
        "banca": "ESA",
        "ano": 2026,
        "enunciado": r"""O pelotão de obras da Escola de Sargentos das Armas recebeu a missão de reconhecimento topográfico, que consiste em calcular a área de um terreno triangular $ABC$, ilustrado na figura abaixo.

Os pontos $A$ e $B$ foram acessados normalmente, mas o ponto $C$ estava dentro de uma área minada, portanto, inacessível por questões de segurança. Para cumprir a missão, o comandante do pelotão mediu os ângulos $C\hat{A}B$, $C\hat{B}A$ e a distância $AB$, obtendo, respectivamente, $\alpha$, $\beta$ e $a$. Qual a área do triângulo encontrada pelo comandante?

(A) $\frac{a^2 \operatorname{sen}\alpha \cdot \operatorname{sen}\beta}{2\operatorname{sen}(\alpha+\beta)}$  
(B) $\frac{a^2 \operatorname{sen}\alpha}{\operatorname{sen}\alpha + \operatorname{sen}\beta}$  
(C) $\frac{a^2 \operatorname{sen}\beta}{\operatorname{sen}\alpha + \operatorname{sen}\beta}$  
(D) $\frac{a^2 \operatorname{sen}(\alpha+\beta)}{2\operatorname{sen}\alpha \cdot \operatorname{sen}\beta}$  
(E) $\frac{a^2 \operatorname{sen}(\alpha+\beta)}{\operatorname{sen}\alpha \cdot \operatorname{sen}\beta}$""",
        "gabarito": "A",
        "figura_path": "data/uploads/esa_2026_q09.svg",
        "estrategias_esperadas": [
            "Lei dos Senos",
            r"Fórmula Trigonométrica da Área $S = \frac{1}{2}bc\operatorname{sen}\alpha$",
            "Propriedade do Seno do Ângulo Suplementar"
        ]
    },

    # Questão 10
    {
        "materia": "Geometria Espacial",
        "topico": "Geometria de Posição",
        "subtopico": "Posições Relativas de Retas e Planos no Espaço",
        "dificuldade": None,
        "banca": "ESA",
        "ano": 2026,
        "enunciado": r"""Observe o paralelepípedo $ABCDEFGH$.

Marque a única alternativa correta entre as afirmações abaixo:

(A) As retas $\overleftrightarrow{BE}$ e $\overleftrightarrow{FG}$ são coplanares.  
(B) Os vértices $A$, $B$ e $G$ não definem um plano.  
(C) As retas $\overleftrightarrow{BC}$ e $\overleftrightarrow{EF}$ são ortogonais.  
(D) As retas $\overleftrightarrow{AE}$ e $\overleftrightarrow{BF}$ são reversas.  
(E) Os vértices $C$, $E$, $H$ e $G$ pertencem a um mesmo plano.""",
        "gabarito": "C",
        "figura_path": "data/uploads/esa_2026_q10.svg",
        "estrategias_esperadas": [
            "Definição de Retas Ortogonais vs Perpendiculares",
            "Postulado de Determinação de Planos por Três Pontos",
            "Classificação de Retas Coplanares e Reversas"
        ]
    },

    # Questão 11
    {
        "materia": "Álgebra",
        "topico": "Sequências e Logaritmos",
        "subtopico": "Propriedades Operatórias de Logaritmos e Soma da PG Finita",
        "dificuldade": None,
        "banca": "ESA",
        "ano": 2026,
        "enunciado": r"""Se $\log_{\left(\sqrt[108]{\frac{1}{\sqrt{3}}}\right)} \sqrt[4]{3}, \log_{\left(\sqrt[18]{\frac{1}{\sqrt{3}}}\right)} \sqrt{3}, \log (\sqrt{10})^{-6}$ formam nessa ordem uma PG, qual o valor aproximado da soma dos 8 primeiros termos:

(A) -20,25  
(B) 20,25  
(C) 25,25  
(D) -25,25  
(E) -23,25""",
        "gabarito": "A",
        "figura_path": None,
        "estrategias_esperadas": [
            "Propriedades de Expoente na Base e Logaritmando",
            "Cálculo da Razão de Progressão Geométrica",
            "Fórmula da Soma dos Termos de PG Finita"
        ]
    },

    # Questão 12
    {
        "materia": "Probabilidade",
        "topico": "Probabilidade Condicional",
        "subtopico": "Amostragem sem Reposição em Baralho",
        "dificuldade": None,
        "banca": "ESA",
        "ano": 2026,
        "enunciado": r"""Um baralho possui 52 cartas, que são divididas em 4 naipes diferentes (ouros, copas, paus e espadas), cada um destes possui 13 cartas, das quais são: 9 numéricas de "2 a 10", Valete (J), Dama (Q), Rei (K) e Ás (A). A probabilidade de a primeira carta retirada ser um REI e a segunda carta NÃO ser REI nem DAMA é:

(A) $\frac{44}{663}$  
(B) $\frac{45}{663}$  
(C) $\frac{176}{663}$  
(D) $\frac{48}{663}$  
(E) $\frac{50}{663}$""",
        "gabarito": "A",
        "figura_path": None,
        "estrategias_esperadas": [
            "Regra da Multiplicação de Probabilidades",
            "Probabilidade Condicional sem Reposição",
            "Contagem de Casos Favoráveis e Espaço Amostral"
        ]
    }
]

# Insere todas as 12 questões no SQLite:
for q in questoes_esa_2026:
    id_q = inserir_questao(
        materia=q["materia"],
        topico=q["topico"],
        subtopico=q["subtopico"],
        dificuldade=q["dificuldade"],
        banca=q["banca"],
        ano=q["ano"],
        enunciado=q["enunciado"],
        gabarito=q["gabarito"],
        figura_path=q["figura_path"],
        estrategias_esperadas=q["estrategias_esperadas"]
    )
    print(f"✅ Questão {id_q:02d} cadastrada: [{q['topico']}]")

print(f"\n🎉 Concluído! {len(questoes_esa_2026)} questões inseridas no banco.")

✅ Questão 01 cadastrada: [Funções]
✅ Questão 02 cadastrada: [Função Logarítmica]
✅ Questão 03 cadastrada: [Combinações com Repetição]
✅ Questão 04 cadastrada: [Relações Métricas e Cevianas]
✅ Questão 05 cadastrada: [Conjuntos e Probabilidade]
✅ Questão 06 cadastrada: [Medidas de Tendência Central]
✅ Questão 07 cadastrada: [Polinômios]
✅ Questão 08 cadastrada: [Cilindros e Esferas]
✅ Questão 09 cadastrada: [Área de Triângulos]
✅ Questão 10 cadastrada: [Geometria de Posição]
✅ Questão 11 cadastrada: [Sequências e Logaritmos]
✅ Questão 12 cadastrada: [Probabilidade Condicional]

🎉 Concluído! 12 questões inseridas no banco.

In [3]:
from datasets import load_dataset

dataset = load_dataset("ShadenA/MathNet", split="train")

df_original = dataset.to_pandas()

df = df_original.copy()

# Traduzir colunas para PT-BR
df = df.rename(columns={
    'problem_markdown': 'enunciado',
    'solutions_markdown': 'solucao_markdown',
    'images': 'imagens',
    'country': 'pais',
    'competition': 'banca',
    'topics_flat': 'topico',
    'language': 'idioma',
    'problem_type': 'tipo_problema',
    'final_answer': 'gabarito'
})

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Resolving data files:   0%|          | 0/56 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/56 [00:00<?, ?it/s]

In [51]:
df_original.to_parquet(
    "../data/mathnet/mathnet_original.parquet",
    index=False
)

In [41]:
df.head()

,id,enunciado,solucao_markdown,imagens,pais,banca,topico,idioma,tipo_problema,gabarito
0,009s,Each cell of an $n \times n$ grid square is co...,"[Color row 1 black and rows 2, 3 white. Then e...",[{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIH...,Argentina,NATIONAL XXX OMA,[Discrete Mathematics > Combinatorics > Colori...,NaN,proof and answer,n ≡ 1 (mod 3)
1,00hy,"There are $n$ line segments on the plane, no t...",[Draw a circle that encloses all the intersect...,[{'bytes': b'\xff\xd8\xff\xdb\x00\x84\x00\x08\...,Asia Pacific Mathematics Olympiad (APMO),APMO,[Geometry > Plane Geometry > Miscellaneous > C...,English,proof only,NaN
2,00k4,Let $ABCDEF$ be a regular octahedron with lowe...,[![](attached_image_1.png)\nWe intersect the e...,[{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIH...,Austria,AustriaMO2013,"[Geometry > Solid Geometry > 3D Shapes, Geomet...",English,proof only,NaN
3,00rl,The point $M$ lies on the side $AB$ of the cir...,[Lemma. Let $I$ be the incenter of $\triangle ...,[{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIH...,Balkan Mathematical Olympiad,BMO 2016 Short List Final,[Geometry > Plane Geometry > Triangles > Trian...,NaN,proof only,NaN
4,00xp,Problem:\n\nA square is divided into 16 equal ...,[Solution:\n\nThe example in Figure 3a demonst...,[{'bytes': b'\xff\xd8\xff\xdb\x00\x84\x00\x08\...,Baltic Way,Baltic Way 1993,[Discrete Mathematics > Combinatorics > Colori...,NaN,proof and answer,8

In [42]:
print(df.columns)

Index(['id', 'enunciado', 'solucao_markdown', 'imagens', 'pais', 'banca',
       'topico', 'idioma', 'tipo_problema', 'gabarito'],
      dtype='str')

In [43]:
df["pais"].value_counts()

pais
United States                                      4819
Romania                                            1905
Brazil                                             1281
Slovenia                                            991
Saudi Arabia                                        908
Baltic Way                                          853
Ukraine                                             847
France                                              816
China                                               719
Philippines                                         710
Italy                                               673
Croatia                                             659
Spain                                               607
Mongolia                                            589
Belarus                                             579
Soviet Union                                        549
Bulgaria                                            546
Netherlands                                         542
Argentina                                           532
Taiwan                                              527
Estonia                                             522
Ireland                                             500
Switzerland                                         475
Hong Kong                                           469
Iran                                                402
North Macedonia                                     385
Russia                                              382
IMO                                                 372
JBMO                                                368
Japan                                               350
Turkey                                              326
South Africa                                        299
Canada                                              291
India                                               272
Balkan Mathematical Olympiad                        263
Vietnam                                             259
Greece                                              240
Austria                                             235
Czech Republic                                      214
Moldova                                             149
Middle European Mathematical Olympiad (MEMO)        145
Singapore                                           143
Nordic Mathematical Olympiad                        134
Germany                                             128
Asia Pacific Mathematics Olympiad (APMO)            124
Ibero-American Mathematical Olympiad                102
New Zealand                                          82
Thailand                                             82
Serbia                                               80
Czech-Polish-Slovak Mathematical Match               75
South Korea                                          69
Silk Road Mathematics Competition                    60
Benelux Mathematical Olympiad                        59
European Girls' Mathematical Olympiad (EGMO)         48
Zhautykov Olympiad                                   35
Romanian Master of Mathematics (RMM)                 19
Mexico                                                6
Portuguese Language Countries Olympiad (OMCPLP)       1
Name: count, dtype: int64

In [5]:
for index, row in df.iterrows():
    print(row["competition"])
    print(row["problem_markdown"])

KeyError: 'competition'

In [6]:
import re
# Tenta extrair 4 dígitos (19xx ou 20xx) da coluna 'competition' ou 'id':
df["ano_extraido"] = df["banca"].astype(str).str.extract(r"\b(19\d{2}|20\d{2})\b")

# Se tiver coluna 'id', você pode tentar nela também caso a de cima venha vazia:
# df["ano_extraido"] = df["ano_extraido"].fillna(df["id"].astype(str).str.extract(r"\b(19\d{2}|20\d{2})\b")[0])

In [46]:
df['banca'].value_counts()

banca
Harvard-MIT Mathematics Tournament                                                                     808
Brazilian Mathematical Olympiad                                                                        552
Baltic Way                                                                                             258
Iranian Mathematical Olympiad                                                                          249
Harvard-MIT Math Tournament                                                                            245
                                                                                                      ...
21. tekmovanje v znanju matematike za dijake srednjih tehniških i strokovnih šol Odbirno tekmovanje      1
28th BALKAN MATHEMATICAL OLYMPIAD                                                                        1
33rd Balkan Mathematical Olympiad                                                                        1
26th Balkan Mathematical Olympiad                                                                        1
The Seventeenth Hong Kong (China) Mathematical Olympiad                                                  1
Name: count, Length: 1482, dtype: int64

In [47]:
df['ano_extraido'].isnull().sum()

np.int64(23157)

In [48]:
df.columns

Index(['id', 'enunciado', 'solucao_markdown', 'imagens', 'pais', 'banca',
       'topico', 'idioma', 'tipo_problema', 'gabarito', 'ano_extraido'],
      dtype='str')

In [7]:
# 2. Se falhou, busca na coluna 'id'
df["ano_extraido"] = df["ano_extraido"].fillna(
    df["id"].astype(str).str.extract(r"\b(19\d{2}|20\d{2})\b")[0]
)
# 3. Se ainda falhou, busca no comecinho do enunciado
df["ano_extraido"] = df["ano_extraido"].fillna(
    df["enunciado"].astype(str).str[:100].str.extract(r"\b(19\d{2}|20\d{2})\b")[0]
)
# Veja quantas sobraram sem ano agora:
print("Ainda sem ano:", df["ano_extraido"].isna().sum())

Ainda sem ano: 21746

In [50]:
# 2. Remove o ano do nome da competição e tira espaços/traços extras das pontas
df["banca"] = df["banca"].str.replace(r"\b(19\d{2}|20\d{2})\b", "", regex=True).str.strip(" -_,")

In [51]:
df.rename(columns={"ano_extraido": "ano"}, inplace=True)

In [52]:
print(df[["banca", "ano"]].head(10))

                                   banca   ano
0                       NATIONAL XXX OMA   NaN
1                                   APMO   NaN
2                          AustriaMO2013   NaN
3                  BMO  Short List Final  2016
4                             Baltic Way  1993
5  60th Belarusian Mathematical Olympiad   NaN
6     15th Benelux Mathematical Olympiad   NaN
7                                    NaN   NaN
8                      Autumn tournament   NaN
9         Canadian Mathematical Olympiad   NaN

In [8]:
# Regex que pega o ano MESMO se estiver grudado em letras (como AustriaMO2013)
regex_ano = r'(19\d{2}|20\d{2})'

# 1. Pega o ano na competition, no id ou no comecinho do enunciado
ano_comp = df['banca'].astype(str).str.extract(regex_ano)[0]
ano_id = df['id'].astype(str).str.extract(regex_ano)[0]
ano_texto = df['enunciado'].astype(str).str[:150].str.extract(regex_ano)[0]

# Combina em ordem de prioridade:
df['ano'] = ano_comp.fillna(ano_id).fillna(ano_texto)

# 2. Limpa a banca tirando o ano (mesmo grudado, tipo AustriaMO2013 -> AustriaMO)
df['banca'] = df['banca'].astype(str).str.replace(regex_ano, '', regex=True).str.strip(' -_,')

In [9]:
import sys
from pathlib import Path
sys.path.append(str(Path.cwd().parent))

import pandas as pd
from src.database.db import pegar_conexao

con = pegar_conexao()
df_usuarios = pd.read_sql("SELECT id, nome, email, celular, cidade, estado, verificado, criado_em FROM usuarios", con)

C:\Users\Guilherme\AppData\Local\Temp\ipykernel_25120\1446790331.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_usuarios = pd.read_sql("SELECT id, nome, email, celular, cidade, estado, verificado, criado_em FROM usuarios", con)

In [55]:
df.columns

Index(['id', 'enunciado', 'solucao_markdown', 'imagens', 'pais', 'banca',
       'topico', 'idioma', 'tipo_problema', 'gabarito', 'ano'],
      dtype='str')

In [56]:
df['idioma']

0                     NaN
1                 English
2                 English
3                     NaN
4                     NaN
               ...
27812                 NaN
27813    Chinese; English
27814             English
27815             English
27816                 NaN
Name: idioma, Length: 27817, dtype: str

In [57]:
df['pais'].value_counts()

pais
United States                                      4819
Romania                                            1905
Brazil                                             1281
Slovenia                                            991
Saudi Arabia                                        908
Baltic Way                                          853
Ukraine                                             847
France                                              816
China                                               719
Philippines                                         710
Italy                                               673
Croatia                                             659
Spain                                               607
Mongolia                                            589
Belarus                                             579
Soviet Union                                        549
Bulgaria                                            546
Netherlands                                         542
Argentina                                           532
Taiwan                                              527
Estonia                                             522
Ireland                                             500
Switzerland                                         475
Hong Kong                                           469
Iran                                                402
North Macedonia                                     385
Russia                                              382
IMO                                                 372
JBMO                                                368
Japan                                               350
Turkey                                              326
South Africa                                        299
Canada                                              291
India                                               272
Balkan Mathematical Olympiad                        263
Vietnam                                             259
Greece                                              240
Austria                                             235
Czech Republic                                      214
Moldova                                             149
Middle European Mathematical Olympiad (MEMO)        145
Singapore                                           143
Nordic Mathematical Olympiad                        134
Germany                                             128
Asia Pacific Mathematics Olympiad (APMO)            124
Ibero-American Mathematical Olympiad                102
New Zealand                                          82
Thailand                                             82
Serbia                                               80
Czech-Polish-Slovak Mathematical Match               75
South Korea                                          69
Silk Road Mathematics Competition                    60
Benelux Mathematical Olympiad                        59
European Girls' Mathematical Olympiad (EGMO)         48
Zhautykov Olympiad                                   35
Romanian Master of Mathematics (RMM)                 19
Mexico                                                6
Portuguese Language Countries Olympiad (OMCPLP)       1
Name: count, dtype: int64

In [10]:
df[(df['pais'] == 'China') & (df['idioma'].isna())]

,id,enunciado,solucao_markdown,imagens,pais,banca,topico,idioma,tipo_problema,gabarito,ano_extraido,ano
67,0455,"As illustrated in Fig. 1.1, $ABCDEF$ is a cycl...",[Let $\omega$ be the circumcircle of $\triangl...,[{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIH...,China,China National Team Selection Test,[Geometry > Plane Geometry > Concurrency and C...,NaN,proof only,NaN,NaN,NaN
340,042z,Suppose all the edges of regular triangular py...,[The given conditions show that plane $LMN$ is...,[],China,China Mathematical Competition,[Geometry > Solid Geometry > Other 3D problems...,NaN,final answer only,π/3,NaN,NaN
633,043v,Let $m$ be a real number. If the real and imag...,"[After calculation, we get $z = 1 + i + \frac{...",[],China,China Mathematical Competition,[Algebra > Intermediate Algebra > Complex numb...,NaN,final answer only,−2 < m < 2,NaN,NaN
1072,043x,"Find the largest constant $C > 0$, such that f...","[For sufficiently large $n$, we guess the opti...",[],China,China National Team Selection Test,[Algebra > Algebraic Expressions > Polynomials...,NaN,proof and answer,1/2,NaN,NaN
1166,044u,In a plane rectangular coordinate system $xOy$...,"[Denote the centres $(2, 1)$, $(10, 11)$ of th...",[],China,China Mathematical Competition,[Geometry > Plane Geometry > Analytic / Coordi...,NaN,final answer only,67/20,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
26468,0432,"In convex quadrilateral $ABCD$, $\vec{BC} = 2\...",[$$\n\overrightarrow{PA} + \overrightarrow{PC}...,[],China,China Mathematical Competition,[Geometry > Plane Geometry > Analytic / Coordi...,NaN,final answer only,337/2021,NaN,2020
26815,043y,"Given positive integers $a$, $b$, $c$ which ar...",[Consider the generating function of $\{f(n)\}...,[],China,China National Team Selection Test,[Discrete Mathematics > Combinatorics > Genera...,NaN,proof only,NaN,NaN,NaN
27293,044z,Sequence $\{a_n\}$ satisfies $a_1 = a_2 = a_3$...,"[By the condition, we know that $b_n = b_1 \cd...",[],China,China Mathematical Competition,[Algebra > Algebraic Expressions > Sequences a...,NaN,proof and answer,(3^{100} + 10)/13,NaN,NaN
27551,043r,"Given $2021$ distinct positive integers $a_1, ...","[Let $k=2021$. In fact, we will prove the stat...",[],China,China National Team Selection Test,[Number Theory > Number-Theoretic Functions > ...,NaN,proof only,NaN,2021,2021
27593,044j,"Find the smallest real number $\alpha$, such t...",[(i) If $M$ is outside $P$ or on the boundary....,[],China,China National Team Selection Test,[Geometry > Plane Geometry > Combinatorial Geo...,NaN,proof and answer,2,NaN,NaN

In [43]:
pip install langdetect

Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ---------------------------------------- 0.0/981.5 kB ? eta -:--:--
     ---------------------------------------- 981.5/981.5 kB 20.5 MB/s  0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: six in c:\Users\Guilherme\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from langdetect) (1.17.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (pyproject.toml): started
  Building wheel for langdetect (pyproject.toml): finished with status 'done'
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=1019155 sha256=9aef45b3bdcc1dd7cdd45938210501a6e09c3a152325773fb0c82706faee3b8e
  Stored in directory: c:\users\guilherme\appdata\local\pip\cache\wheels\13\60\5a\f2012969b3f7413b62b7b7063d6c9b45c93004a978cbe8ea2f
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9
Note: you may need to restart the kernel to use updated packages.

In [11]:
from langdetect import detect

texto = """
Olá tudo bem
"""

idioma = detect(texto)

print(idioma)

pt

In [12]:
texto = """
设 ABCD 是一个矩形...
"""

print(detect(texto))

zh-cn

,id,enunciado,solucao_markdown,imagens,pais,banca,topico,idioma,tipo_problema,gabarito,ano
0,009s,Each cell of an $n \times n$ grid square is co...,"[Color row 1 black and rows 2, 3 white. Then e...",[{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIH...,Argentina,NATIONAL XXX OMA,[Discrete Mathematics > Combinatorics > Colori...,NaN,proof and answer,n ≡ 1 (mod 3),NaN
1,00hy,"There are $n$ line segments on the plane, no t...",[Draw a circle that encloses all the intersect...,[{'bytes': b'\xff\xd8\xff\xdb\x00\x84\x00\x08\...,Asia Pacific Mathematics Olympiad (APMO),APMO,[Geometry > Plane Geometry > Miscellaneous > C...,English,proof only,NaN,NaN
2,00k4,Let $ABCDEF$ be a regular octahedron with lowe...,[![](attached_image_1.png)\nWe intersect the e...,[{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIH...,Austria,AustriaMO,"[Geometry > Solid Geometry > 3D Shapes, Geomet...",English,proof only,NaN,NaN
3,00rl,The point $M$ lies on the side $AB$ of the cir...,[Lemma. Let $I$ be the incenter of $\triangle ...,[{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIH...,Balkan Mathematical Olympiad,BMO Short List Final,[Geometry > Plane Geometry > Triangles > Trian...,NaN,proof only,NaN,NaN
4,00xp,Problem:\n\nA square is divided into 16 equal ...,[Solution:\n\nThe example in Figure 3a demonst...,[{'bytes': b'\xff\xd8\xff\xdb\x00\x84\x00\x08\...,Baltic Way,Baltic Way,[Discrete Mathematics > Combinatorics > Colori...,NaN,proof and answer,8,NaN

In [63]:
df["pais"].value_counts(dropna=False).head(50)

pais
United States                                   4819
Romania                                         1905
Brazil                                          1281
Slovenia                                         991
Saudi Arabia                                     908
Baltic Way                                       853
Ukraine                                          847
France                                           816
China                                            719
Philippines                                      710
Italy                                            673
Croatia                                          659
Spain                                            607
Mongolia                                         589
Belarus                                          579
Soviet Union                                     549
Bulgaria                                         546
Netherlands                                      542
Argentina                                        532
Taiwan                                           527
Estonia                                          522
Ireland                                          500
Switzerland                                      475
Hong Kong                                        469
Iran                                             402
North Macedonia                                  385
Russia                                           382
IMO                                              372
JBMO                                             368
Japan                                            350
Turkey                                           326
South Africa                                     299
Canada                                           291
India                                            272
Balkan Mathematical Olympiad                     263
Vietnam                                          259
Greece                                           240
Austria                                          235
Czech Republic                                   214
Moldova                                          149
Middle European Mathematical Olympiad (MEMO)     145
Singapore                                        143
Nordic Mathematical Olympiad                     134
Germany                                          128
Asia Pacific Mathematics Olympiad (APMO)         124
Ibero-American Mathematical Olympiad             102
New Zealand                                       82
Thailand                                          82
Serbia                                            80
Czech-Polish-Slovak Mathematical Match            75
Name: count, dtype: int64

In [65]:
df["banca"].value_counts(dropna=False).head(50)

banca
Harvard-MIT Mathematics Tournament                  808
HMMT November                                       719
HMMT February                                       616
Brazilian Mathematical Olympiad                     552
Baltic Way                                          545
NaN                                                 434
Iranian Mathematical Olympiad                       249
Harvard-MIT Math Tournament                         245
Mathematica competitions in Croatia                 240
Canadian Mathematical Olympiad                      224
Mongolian Mathematical Olympiad                     222
SAUDI ARABIAN MATHEMATICAL COMPETITIONS             216
IRL_ABooklet                                        211
PRÉPARATION OLYMPIQUE FRANÇAISE DE MATHÉMATIQUES    205
Berkeley Math Circle                                201
Harvard-MIT November Tournament                     185
China Mathematical Competition                      173
HMMT                                                173
IMO HK TST                                          165
Estonian Math Competitions                          159
ASU                                                 155
SAMC                                                147
Olympiades Françaises de Mathématiques              139
Estonian Mathematical Olympiad                      137
National Math Olympiad                              134
Japan Mathematical Olympiad                         130
Team Selection Test                                 130
Bulgarian Mathematical Competitions                 127
Nível 2                                             120
Saudi Arabia Mathematical Competitions              120
Ireland                                             119
IMO Selektion                                       115
Saudi Arabian IMO Booklet                           112
Belarusian Mathematical Olympiad                    112
Préparation Olympique Française de Mathématiques    109
IMO  Shortlisted Problems                           109
INMO                                                107
Junior Balkan Mathematical Olympiad                 106
Iberoamerican Mathematical Olympiad                 102
Progetto Olimpiadi di Matematica                    100
CHKMO                                                94
International Mathematical Olympiad                  92
Macedonian Mathematical Competitions                 92
Romanian Mathematical Olympiad                       91
Olimpiada Republicană la Matematică                  89
Balkan Mathematical Olympiad                         87
Singapore Mathematical Olympiad (SMO)                86
Baltic Way  Shortlist                                86
XL Russian mathematical olympiad                     85
APMO                                                 84
Name: count, dtype: int64

In [66]:
df[["pais", "banca", "ano"]].drop_duplicates().head(100)

,pais,banca,ano
0,Argentina,NATIONAL XXX OMA,NaN
1,Asia Pacific Mathematics Olympiad (APMO),APMO,NaN
2,Austria,AustriaMO,NaN
3,Balkan Mathematical Olympiad,BMO Short List Final,NaN
4,Baltic Way,Baltic Way,NaN
...,...,...,...
104,Switzerland,Vorrundenprüfung,NaN
105,Taiwan,二〇一五數學奧林匹亞競賽第三階段選訓營,NaN
107,Turkey,21st Turkish Mathematical Olympiad,NaN
108,Ukraine,55rd Ukrainian National Mathematical Olympiad ...,NaN
109,United States,19th Bay Area Mathematical Olympiad,NaN

In [ ]:
df[["pais", "banca", "idioma", "tipo_problema", "ano"]].sample(50, random_state=42).head(50)

,pais,banca,idioma,tipo_problema,ano
18651,United States,USA IMO TST,NaN,proof only,NaN
6091,United States,Harvard-MIT Mathematics Tournament,NaN,proof only,NaN
18098,Russia,XL Russian mathematical olympiad,NaN,proof and answer,NaN
26649,Netherlands,Junior Mathematical Olympiad,NaN,MCQ,NaN
9072,France,PRÉPARATION OLYMPIQUE FRANÇAISE DE MATHÉMATIQUES,NaN,proof and answer,NaN
11444,United States,Harvard-MIT Math Tournament,NaN,final answer only,NaN
23815,Slovenia,63. matematično tekmovanje srednješolcev Slove...,NaN,proof and answer,NaN
17103,Philippines,23rd Philippine Mathematical Olympiad,NaN,proof and answer,NaN
12636,United States,HMMT February,NaN,proof and answer,NaN
9038,Baltic Way,Baltic Way Problem Shortlist,NaN,proof and answer,NaN
17760,Turkey,IMO TEAM SELECTION EXAM,English,proof and answer,2003
17156,Iran,Iranian Mathematical Olympiad,English,proof only,NaN
22111,Saudi Arabia,Saudi Arabian IMO Booklet,English,proof only,NaN
20692,Brazil,Brazilian Mathematical Olympiad,NaN,final answer only,NaN
22664,Croatia,Mathematica competitions in Croatia,English,proof and answer,NaN
8034,Philippines,13th Philippine Mathematical Olympiad,NaN,final answer only,NaN
12679,Ukraine,60th Ukrainian National Mathematical Olympiad,NaN,proof only,NaN
10880,Slovenia,10. tekmovanje v znanju matematike za dijake s...,NaN,proof and answer,NaN
4932,Brazil,Brazilian Mathematical Olympiad,NaN,proof and answer,NaN
24862,Canada,Canadian Mathematical Olympiad,NaN,proof only,NaN
15786,Croatia,Croatian Mathematical Olympiad,English,proof only,NaN
22121,China,Chinese Mathematical Olympiad,English,proof and answer,NaN
11854,Romania,Ninth STARS OF MATHEMATICS Competition,English,proof only,NaN
12626,Iran,27th Iranian Mathematical Olympiad,NaN,proof only,NaN
19597,India,INMO,NaN,proof only,NaN
20123,France,Préparation Olympique Française de Mathématiques,NaN,proof and answer,NaN
26179,Brazil,Desafios,NaN,proof only,NaN
27692,United States,Berkeley Math Circle: Monthly Contest 6,NaN,proof and answer,NaN
16454,Romania,Seventeenth Stars of Mathematics Competition,English,proof and answer,NaN
17151,China,China Girls' Mathematical Olympiad,English,proof and answer,2011
15497,United States,Harvard-MIT Mathematics Tournament,NaN,final answer only,NaN
7886,Slovenia,National Math Olympiad,NaN,proof and answer,NaN
21992,Belarus,Belarusian Mathematical Olympiad,English,proof and answer,NaN
4794,United States,HMMT February,NaN,proof and answer,2015
26613,Soviet Union,17th ASU,NaN,proof only,NaN
7545,Romania,THE 68th ROMANIAN MATHEMATICAL OLYMPIAD,English,proof and answer,NaN
18187,Romania,69th NMO Selection Tests for JBMO,NaN,proof only,NaN
9755,China,International Mathematical Olympiad,English,proof and answer,NaN
3193,United States,1st Annual Harvard-MIT November Tournament,NaN,proof and answer,NaN
13692,France,PRÉPARATION OLYMPIQUE FRANÇAISE DE MATHÉMATIQUES,NaN,proof only,NaN
20395,India,IMO TST,NaN,proof only,NaN
12739,Croatia,Mathematica competitions in Croatia,English,proof only,NaN
18862,Philippines,Philippines Mathematical Olympiad,NaN,final answer only,NaN
11522,United States,HMMT February,NaN,final answer only,NaN
11274,Brazil,NaN,NaN,proof only,NaN
24431,Nordic Mathematical Olympiad,"Nordic Mathematical Contest, NMC 1",NaN,proof only,NaN
12698,United States,Harvard-MIT Mathematics Tournament,NaN,proof and answer,NaN
14550,Moldova,Olimpiada Republicană la Matematică,NaN,proof only,NaN
10947,Philippines,QUALIFYING STAGE,NaN,MCQ,NaN
3077,Italy,Progetto Olimpiadi di Matematica - GARA di SEC...,NaN,MCQ,NaN

In [69]:
def normalizar_tipo_problema(tipo):
    if tipo == "MCQ":
        return "multipla_escolha"
    
    if tipo in [
        "proof only",
        "proof and answer",
        "answer only"
    ]:
        return "discursiva"
    
    return None

In [70]:
df["tipo_problema_normalizado"] = df["tipo_problema"].apply(normalizar_tipo_problema)

In [71]:
df['tipo_problema_normalizado'].value_counts()

tipo_problema_normalizado
discursiva          24815
multipla_escolha     1126
Name: count, dtype: int64

In [72]:
amostra = df[[
    "id",
    "pais",
    "banca",
    "ano",
    "idioma",
    "tipo_problema"
]].sample(100, random_state=42)

amostra

,id,pais,banca,ano,idioma,tipo_problema
18651,0kft,United States,USA IMO TST,NaN,NaN,proof only
6091,0i7q,United States,Harvard-MIT Mathematics Tournament,NaN,NaN,proof only
18098,0csr,Russia,XL Russian mathematical olympiad,NaN,NaN,proof and answer
26649,0a2s,Netherlands,Junior Mathematical Olympiad,NaN,NaN,MCQ
9072,05wr,France,PRÉPARATION OLYMPIQUE FRANÇAISE DE MATHÉMATIQUES,NaN,NaN,proof and answer
...,...,...,...,...,...,...
5915,061w,Germany,Auswahlwettbewerb zur IMO,NaN,NaN,proof and answer
27722,0d0e,Saudi Arabia,Saudi Arabia Mathematical Competitions,NaN,English,proof and answer
9559,0ga8,Taiwan,二〇一六數學奧林匹亞競賽第三階段選訓營,NaN,NaN,proof and answer
6595,0j7y,United States,Harvard-MIT November Tournament,NaN,NaN,proof and answer
1441,00ri,Balkan Mathematical Olympiad,BMO Short List Final,NaN,NaN,proof only

In [73]:
banca = df['banca']

In [77]:
banca.to_csv("questoes_banca.csv", index=False, encoding="utf-8-sig")

In [ ]:
def detectar_idioma(row):
    if pd.notna(idioma):
        return idioma

## 📥 Extração e Importação de Questões do ENEM (via biblioteca `enem`)

Esta seção utiliza o pacote **Enem Extractor** (`enem`) para:
1. Ler o PDF oficial de uma prova do ENEM (Dia 2 - Matemática e Ciências da Natureza).
2. Extrair o texto das questões, alternativas (A, B, C, D, E) e o gabarito oficial em JSON.
3. Recortar e salvar automaticamente as **figuras e gráficos** das questões.
4. Inserir as questões de Matemática (136 a 180) diretamente no banco de dados do **MathAI** (`questoes` no Turso/SQLite).

In [ ]:
# Instala a biblioteca enem se ainda não estiver instalada
#!pip install enem
import os
import sys
import json
import shutil
import subprocess
from pathlib import Path

# Garante acesso à raiz do projeto
BASE_DIR = Path.cwd().parent
sys.path.append(str(BASE_DIR))

from src.database.db import pegar_conexao
print("✅ Ambiente configurado para importação do ENEM!")

Collecting enem
  Downloading enem-1.0.4-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: pygments in C:\Users\Guilherme\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from enem) (2.21.0)
Requirement already satisfied: colorama in C:\Users\Guilherme\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from enem) (0.4.6)
Requirement already satisfied: pillow in C:\Users\Guilherme\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from enem) (12.3.0)
Collecting PyMuPDF (from enem)
  Downloading pymupdf-1.28.2-cp310-abi3-win_amd64.whl.metadata (26 kB)
Downloading enem-1.0.4-py3-none-any.whl (13 kB)
Downloading pymupdf-1.28.2-cp310-abi3-win_amd64.whl (19.8 MB)
   ---------------------------------------- 0.0/19.8 MB ? eta -:--:--
   ------------ --------------------------- 6.0/19.8 MB 33.9 MB/s eta 0:00:01
   ------------------------- -------------- 12.6/19.8 MB 31.6 MB/s eta 0:00:01
   ---------------------------------- ----- 17.3/19.8 MB 28.6 MB/s eta 0:00:01
   ---------------------------------------  19.7/19.8 MB 27.9 MB/s eta 0:00:01
   ---------------------------------------- 19.8/19.8 MB 23.6 MB/s  0:00:00
Installing collected packages: PyMuPDF, enem

   ---------------------------------------- 0/2 [PyMuPDF]
   ---------------------------------------- 0/2 [PyMuPDF]
   ---------------------------------------- 0/2 [PyMuPDF]
   ---------------------------------------- 0/2 [PyMuPDF]
   -------------------- ------------------- 1/2 [enem]
   ---------------------------------------- 2/2 [enem]

Successfully installed PyMuPDF-1.28.2 enem-1.0.4

  WARNING: The script pymupdf.exe is installed in 'C:\Users\Guilherme\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script enem.exe is installed in 'C:\Users\Guilherme\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

ModuleNotFoundError: No module named 'path'

In [6]:
def extrair_e_importar_enem(
    caminho_pdf_prova: str,
    caminho_pdf_gabarito: str | None = None,
    ano: int = 2023,
    pasta_saida: str = "../data/enem_extraido",
    questoes_apenas_matematica: bool = True
):
    """
    Executa a extração do ENEM via CLI do 'enem', processa o JSON gerado,
    copia as imagens para data/uploads/ e insere no banco de dados do MathAI.
    """
    pasta_saida_path = Path(pasta_saida)
    pasta_saida_path.mkdir(parents=True, exist_ok=True)
    pasta_uploads = BASE_DIR / "data" / "uploads"
    pasta_uploads.mkdir(parents=True, exist_ok=True)

    cmd = [sys.executable, "-m", "enem", str(caminho_pdf_prova), "-o", str(pasta_saida_path)]
    if caminho_pdf_gabarito:
        cmd.extend(["-g", str(caminho_pdf_gabarito)])

    print(f"🚀 Executando Enem Extractor para o ENEM {ano}...")
    resultado = subprocess.run(cmd, capture_output=True, text=True)
    if resultado.returncode != 0:
        print(f"❌ Erro na extração do ENEM:\n{resultado.stderr}")
        return 0

    print("✅ Extração do PDF concluída com sucesso! Processando questões...")

    # Localiza o arquivo JSON gerado na pasta de saída
    arquivos_json = list(pasta_saida_path.glob("*.json"))
    if not arquivos_json:
        print("⚠️ Nenhum arquivo JSON encontrado na pasta de saída.")
        return 0

    with open(arquivos_json[0], "r", encoding="utf-8") as f:
        dados_enem = json.load(f)

    con = pegar_conexao()
    cur = con.cursor()
    total_inseridas = 0

    questoes_lista = dados_enem if isinstance(dados_enem, list) else dados_enem.get("questions", [])

    for q in questoes_lista:
        num = q.get("number") or q.get("index") or 0
        # No 2º dia do ENEM (a partir de 2009), Matemática vai da questão 136 até a 180
        if questoes_apenas_matematica and not (136 <= int(num) <= 180):
            continue

        enunciado = q.get("statement", "") or q.get("enunciado", "") or q.get("text", "")
        alternativas = q.get("alternatives", {}) or q.get("options", {})
        
        texto_completo = enunciado.strip()
        if alternativas:
            texto_completo += "\n\n"
            for letra in ["A", "B", "C", "D", "E"]:
                if letra in alternativas:
                    texto_completo += f"({letra}) {alternativas[letra]}\n"

        gabarito = str(q.get("answer") or q.get("gabarito") or "").strip().upper()

        figura_relativa = None
        imagem_origem = q.get("image") or q.get("figure")
        if imagem_origem:
            caminho_img = pasta_saida_path / imagem_origem
            if caminho_img.exists():
                nome_destino = f"enem_{ano}_q{num}_{caminho_img.name}"
                destino = pasta_uploads / nome_destino
                shutil.copy2(caminho_img, destino)
                figura_relativa = f"data/uploads/{nome_destino}"

        try:
            cur.execute("""
                INSERT INTO questoes (
                    materia, topico, enunciado, gabarito, dificuldade,
                    banca, ano, figura_path, tipo
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                "Matemática", "ENEM", texto_completo, gabarito, 3,
                "ENEM", ano, figura_relativa, "objetiva"
            ))
            total_inseridas += 1
        except Exception as e:
            print(f"Erro ao inserir questão {num}: {e}")

    con.commit()
    print(f"🎉 ENEM {ano}: {total_inseridas} questões de Matemática importadas com sucesso!\n")
    return total_inseridas


def importar_enem_por_ano(
    ano: int,
    pasta_provas: str = "../data/provas_enem",
    pasta_saida: str = "../data/enem_extraido"
):
    """
    Localiza automaticamente os PDFs da prova e gabarito do ano especificado
    e executa a extração e importação.
    Exemplo de uso em loop:
        for ano in range(2009, 2025):
            importar_enem_por_ano(ano)
    """
    pasta = Path(pasta_provas)
    if not pasta.exists():
        pasta.mkdir(parents=True, exist_ok=True)
        print(f"📁 Pasta criada: {pasta.resolve()}. Coloque os PDFs lá dentro!")
        return 0

    # Procura arquivos PDF do ano especificado
    arquivos_ano = list(pasta.glob(f"*{ano}*.pdf"))
    if not arquivos_ano:
        print(f"⚠️ [ENEM {ano}] Nenhum PDF encontrado contendo '{ano}' em {pasta}. Pulando...")
        return 0

    # Identifica o gabarito e a prova
    gabarito_pdf = None
    prova_pdf = None

    for f in arquivos_ano:
        nome_lower = f.name.lower()
        if "gabarito" in nome_lower or "gab" in nome_lower or "key" in nome_lower:
            gabarito_pdf = str(f)
        elif "dia2" in nome_lower or "matematica" in nome_lower or "mat" in nome_lower or "caderno" in nome_lower or "prova" in nome_lower:
            prova_pdf = str(f)

    # Se não achou prova específica com dia2/mat, pega o primeiro que não for gabarito
    if not prova_pdf:
        candidatos = [str(f) for f in arquivos_ano if str(f) != gabarito_pdf]
        if candidatos:
            prova_pdf = candidatos[0]

    if not prova_pdf:
        print(f"⚠️ [ENEM {ano}] Não foi possível identificar o PDF da prova. Pulando...")
        return 0

    print(f"📄 [ENEM {ano}] Prova: {Path(prova_pdf).name} | Gabarito: {Path(gabarito_pdf).name if gabarito_pdf else 'Nenhum'}")
    return extrair_e_importar_enem(
        caminho_pdf_prova=prova_pdf,
        caminho_pdf_gabarito=gabarito_pdf,
        ano=ano,
        pasta_saida=f"{pasta_saida}/enem_{ano}"
    )

In [18]:
import re
from langdetect import detect, DetectorFactory
from langdetect.lang_detect_exception import LangDetectException

def remover_latex(texto):
    if not isinstance(texto, str):
        return ""

    # Remove blocos $$ ... $$
    texto = re.sub(r"\$\$.*?\$\$", " ", texto, flags=re.DOTALL)

    # Remove expressões $ ... $
    texto = re.sub(r"\$.*?\$", " ", texto, flags=re.DOTALL)

    #Aqui tiramos as quebras de linha

    texto = re.sub(r"\s","",texto).strip()

    return texto

In [19]:
df['enunciado_sem_latex'] = df['enunciado'].apply(remover_latex)

In [14]:
df.columns

Index(['id', 'enunciado', 'solucao_markdown', 'imagens', 'pais', 'banca',
       'topico', 'idioma', 'tipo_problema', 'gabarito', 'ano_extraido', 'ano'],
      dtype='str')

In [20]:
df['enunciado_sem_latex']

0        Eachcellofangridsquareiscoloredblackorwhite.We...
1        Therearelinesegmentsontheplane,nothreeintersec...
2        Letbearegularoctahedronwithlowervertex,upperve...
3        Thepointliesonthesideofthecircumscribedquadril...
4        Problem:Asquareisdividedinto16equalsquares,obt...
                               ...
27812    ComputethesumwhereisthethFibonaccinumbergivenb...
27813    給定一個整數的有限集，是否總是存在一個整係數多項式，使得對於所有整數，為完全平方數若且唯若？...
27814    Weconsiderthenumberwhichconsistsofsixes.Thesqu...
27815    Let.Ifrealnumbersaresuchthatholdsforany,theneq...
27816    Problem:Unfabbrostacostruendounacancellataoriz...
Name: enunciado_sem_latex, Length: 27817, dtype: str

In [22]:
def detectar_idioma_seguro(texto):
    if not texto or len(texto.strip()) < 3:
        return None
    try:
        return detect(texto)
    except LangDetectException:
        return None
    except Exception:
        return None

def processar_idioma(row):
    # 1. Se já veio preenchido no dataset, mantém
    if pd.notna(row["idioma"]) and str(row["idioma"]).strip() not in ["", "nan", "NaN"]:
        return row["idioma"], "dataset"
    
    # 2. Se não veio, tenta detectar a partir do enunciado sem LaTeX
    idioma = detectar_idioma_seguro(row["enunciado_sem_latex"])
    if idioma is not None:
        return idioma, "detector"
    
    # 3. Casos que precisam de revisão manual ou IA posterior
    return None, "revisao"

# Aplica nas linhas criando idioma_final e origem_idioma
res = df.apply(processar_idioma, axis=1)
df["idioma_final"] = [r[0] for r in res]
df["origem_idioma"] = [r[1] for r in res]

In [23]:
print("📊 Origem dos dados de idioma:")
print(df["origem_idioma"].value_counts(dropna=False))

print("\n🌍 Top 15 Idiomas Identificados:")
print(df["idioma_final"].value_counts(dropna=False).head(15))

print(f"\n⚠️ Total de questões sem idioma identificado (revisão): {df['idioma_final'].isna().sum()}")

📊 Origem dos dados de idioma:
origem_idioma
detector    18202
dataset      9610
revisao         5
Name: count, dtype: int64

🌍 Top 15 Idiomas Identificados:
idioma_final
en                  12684
English              8364
pt                   1009
fr                    855
it                    664
de                    621
sl                    597
es                    469
ro                    447
nl                    272
Spanish               259
English; Russian      233
ko                    193
Chinese; English      124
Mongolian             105
Name: count, dtype: int64

⚠️ Total de questões sem idioma identificado (revisão): 5

In [25]:
# Filtra todas as linhas que têm mais de um idioma (separadas por ';')
multilingues = df[df["idioma_final"].astype(str).str.contains(";", na=False)]

print(f"Total de questões com múltiplos idiomas: {len(multilingues)}\n")
print("Distribuição das combinações:")
print(multilingues["idioma_final"].value_counts())

# Amostra de 10 questões para vermos o texto real
multilingues[["id", "pais", "banca", "idioma_final", "enunciado_sem_latex"]].head(10)

Total de questões com múltiplos idiomas: 378

Distribuição das combinações:
idioma_final
English; Russian    233
Chinese; English    124
English; Chinese     21
Name: count, dtype: int64

,id,pais,banca,idioma_final,enunciado_sem_latex
39,0cnn,Russia,Russian mathematical olympiad,English; Russian,Segmentisananglebisectorinatriangle(pointlieso...
138,0cvb,Russia,Final round,English; Russian,"PashaandVovaplaythefollowinggame,makingmovesin..."
143,0cu8,Russia,XLIII Russian mathematical olympiad,English; Russian,"IntheCartesianplane,twographsandofmonicquadrat..."
168,0gfv,Taiwan,"數學奧林匹亞競賽第二階段培訓營, 獨立研究 (二)",Chinese; English,對任一正整數，證明多項式有個實根。(註：為二項式係數。)
264,0cmk,Russia,Russian mathematical olympiad,English; Russian,Konstantinhadtwosetsof17coins:thefirstsetconsi...
343,0gg9,Taiwan,"數學奧林匹亞競賽第五階段培訓營, 國際競賽實作(二)",Chinese; English,設點為圓上的四點，形成一個凸四邊形。設與交於點，且位於之間；又設與交於點。令點為圓上異於的一...
407,0co7,Russia,Final round,English; Russian,Twodistinctrealnumbersandarechoseninsuchawayth...
419,0ggp,Taiwan,"數學奧林匹亞競賽第三階段選訓營, 獨立研究(一)",Chinese; English,設代表所有正整數的集合，代表正整數數對的集合。在所有從到的函數中，對於所有非負整數，我們遞迴...
473,0gii,Taiwan,APMO Taiwan Preliminary Round 1,Chinese; English,考慮多項式函數。設實數滿足將之值寫成，其中為正整數且不被大於1的平方數整除，則之值為⑥⑦。C...
561,0cmw,Russia,Russian mathematical olympiad,English; Russian,"Inacountry,somepairsofcitiesareconnectedbyther..."

In [32]:
import re

MAPA_EXPANDIDO = {
    # Espanhol
    "spanish": "es", "español": "es", "espanol": "es", "castellano": "es",
    # Inglês
    "english": "en", "ingles": "en", "inglês": "en",
    # Português
    "portuguese": "pt", "português": "pt", "portugues": "pt",
    # Francês
    "french": "fr", "français": "fr", "francês": "fr",
    # Alemão
    "german": "de", "deutsch": "de",
    # Italiano
    "italian": "it", "italiano": "it",
    # Chinês
    "chinese": "zh", "chinese (traditional)": "zh", "chinese (simplified)": "zh", "mandarin": "zh",
    # Outros
    "russian": "ru", "mongolian": "mn", "romanian": "ro", "slovenian": "sl",
    "dutch": "nl", "korean": "ko", "turkish": "tr", "greek": "el",
    "ukrainian": "uk", "bulgarian": "bg", "croatian": "hr", "japanese": "ja",
    "czech": "cs", "hungarian": "hu", "polish": "pl", "vietnamese": "vi",
    "estonian": "et", "macedonian": "mk", "arabic": "ar", "hindi": "hi",
    "persian": "fa", "swedish": "sv", "finnish": "fi", "norwegian": "no",
    "catalan": "ca", "danish": "da"
}

def corrigir_idioma(row):
    # Pega o que está em idioma_limpo atualmente
    valor = str(row["idioma_limpo"]).strip().lower() if pd.notna(row["idioma_limpo"]) else ""
    
    # 1. Se tem múltiplos nomes com vírgula ou barra (ex: "english, arabic", "macedonian, english")
    if re.search(r"[,;/]| and ", valor):
        detectado = detectar_idioma_seguro(row["enunciado_sem_latex"])
        if detectado:
            return detectado.split("-")[0]
            
    # 2. Se for um nome por extenso (ex: "español" -> "es", "chinese (traditional)" -> "zh")
    if valor in MAPA_EXPANDIDO:
        return MAPA_EXPANDIDO[valor]
        
    # 3. Se já for código de 2 letras limpo (ex: "en", "pt", "es")
    if len(valor) == 2 and valor.isalpha():
        return valor
        
    # 4. Se tiver hífen (ex: "zh-cn" -> "zh")
    if "-" in valor:
        return valor.split("-")[0]
        
    # 5. Se nada acima resolveu, tenta o detector no texto
    detectado = detectar_idioma_seguro(row["enunciado_sem_latex"])
    if detectado:
        return detectado.split("-")[0]
        
    return None

# Atualiza diretamente a coluna 'idioma_limpo' e 'idioma'
df["idioma_limpo"] = df.apply(corrigir_idioma, axis=1)
df["idioma"] = df["idioma_limpo"]

# Exibe o resultado da própria 'idioma_limpo'
print("🌍 Ranking Final de idioma_limpo:")
print(df["idioma_limpo"].value_counts(dropna=False).head(20))

🌍 Ranking Final de idioma_limpo:
idioma_limpo
en    21353
pt     1010
es      902
fr      858
it      664
de      639
sl      597
ro      447
nl      272
ko      243
ru      200
mk      153
mn      105
zh       96
ca       75
da       64
no       29
hu       28
et       26
hr       15
Name: count, dtype: int64

In [33]:
df['banca']

0                        NATIONAL XXX OMA
1                                    APMO
2                               AustriaMO
3                   BMO  Short List Final
4                              Baltic Way
                       ...
27812       Baltic Way  Problem Shortlist
27813         IMO 1J, Independent Study 2
27814        Junior Mathematical Olympiad
27815      China Mathematical Competition
27816    Progetto Olimpiadi di Matematica
Name: banca, Length: 27817, dtype: str

In [34]:
# Lista todas as bancas que contêm a palavra IMO
df[df["banca"].str.contains(r"\bIMO\b", case=False, na=False)]["banca"].value_counts()

banca
IMO HK TST                   165
IMO Selektion                115
Saudi Arabian IMO Booklet    112
IMO  Shortlisted Problems    109
SAUDI ARABIAN IMO Booklet     77
                            ...
IMO TST Day 3                  2
IMO 3J, Mock Exam 1            2
IMO TST Day 1                  2
IMO TST Day 2                  1
IMO TST Day 4                  1
Name: count, Length: 91, dtype: int64

In [35]:
filtro_geral = (
    df["banca"].str.contains(r"\bIMO\b", case=False, na=False) |
    df["pais"].str.contains(r"\bIMO\b", case=False, na=False)
)

# Visualizar a combinação de país e banca desses casos
df[filtro_geral][["pais", "banca", "ano"]].drop_duplicates()

              pais                                              banca   ano
19       Hong Kong                                         IMO HK TST  1997
20             IMO                          IMO  Shortlisted Problems  2006
32     Netherlands                                  IMO-selectietoets   NaN
52          Turkey                        Team Selection Test for IMO  2007
74         Germany                              2. IMO-Auswahlklausur   NaN
...            ...                                                ...   ...
24906          IMO  53rd International Mathematical Olympiad Short...  2012
26434    Hong Kong                                         IMO HK TST  2024
26464          IMO                              IMO Problem Shortlist  2009
27203    Hong Kong                                         IMO HK TST  2022
27414    Hong Kong                                         IMO HK TST  2004

[192 rows x 3 columns]

In [36]:
filtro_tst = df["banca"].str.contains(r"\b(TST|Selection|Auswahl|Selectie)\b", case=False, na=False)
df[filtro_tst][["pais", "banca"]].drop_duplicates().head(30)

C:\Users\Guilherme\AppData\Local\Temp\ipykernel_25120\3107200362.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  filtro_tst = df["banca"].str.contains(r"\b(TST|Selection|Auswahl|Selectie)\b", case=False, na=False)

                pais                                              banca
19         Hong Kong                                         IMO HK TST
40      Saudi Arabia  Selection tests for the Balkan Mathematical Ol...
52            Turkey                        Team Selection Test for IMO
67             China                 China National Team Selection Test
93           Romania  66th NMO SELECTION TESTS FOR THE BALKAN AND IN...
139          Vietnam                               Team selection tests
160        Hong Kong      IMO Preliminary Selection Contest — Hong Kong
162      Netherlands                                          Dutch TST
200    United States                                Team Selection Test
251           Turkey                                Team Selection Test
254           Turkey                       Team Selection Test for JBMO
285          Romania                           75th NMO Selection Tests
302            India                                      IMO TST Day 2
306      Netherlands                           BxMO Team Selection Test
321  North Macedonia                        Team Selection Test for IMO
337          Belarus                     Selection and Training Session
339            China                  China Team Selection Test for IMO
354    United States                                        USA IMO TST
365          Romania  NMO Selection Tests for the Junior Balkan Math...
367          Romania               SELECTION TESTS FOR THE  BMO AND IMO
394    United States  USA TST Selection Test for 67th IMO and 15th EGMO
411         Bulgaria                    Team selection test for 47. IMO
418     Saudi Arabia                       Team selection tests for BMO
421          Belarus                     SELECTION and TRAINING SESSION
455          Romania  THE 68th NMO SELECTION TESTS FOR THE BALKAN AN...
466          Romania  THE 73rd NMO SELECTION TESTS FOR THE JUNIOR BA...
471        Hong Kong                    Hong Kong Team Selection Test 1
479    United States                            IMO Team Selection Test
528          Romania  THE 68th NMO SELECTION TESTS FOR THE JUNIOR BA...
541          Romania  64th NMO Selection Tests for the Balkan and In...

In [38]:
df[df["pais"] == "Brazil"]["banca"].value_counts(dropna=False)

banca
Brazilian Mathematical Olympiad              552
NaN                                          177
Nível 2                                      120
Brazilian Math Olympiad                       67
Nível 3                                       57
Brazilian Mathematical Olympiad, Nível 2      39
Desafios                                      34
NÍVEL 3                                       32
XXXI Brazilian Math Olympiad                  17
XIV OBM                                        8
Lista 6                                        8
XXIV OBM                                       6
Lista 2                                        6
Brazil                                         6
XVII OBM                                       6
XXV OBM                                        6
XV OBM                                         6
V OBM                                          6
XXII OBM                                       6
IV OBM                                         6
Lista 4                                        6
XVIII OBM                                      6
XXVI OBM                                       6
III OBM                                        6
XXI OBM                                        6
XX OBM                                         6
VI OBM                                         5
VIII OBM                                       5
XXIII OBM                                      5
XVI OBM                                        5
XII OBM                                        5
XI OBM                                         5
XIX OBM                                        5
I OBM                                          5
IX OBM                                         5
XIII OBM                                       4
X OBM                                          4
Al doilea baraj de selecție pentru OBMJ        4
Al patrulea baraj de selecție pentru OBMJ      4
II OBM                                         4
Al treilea baraj de selecție pentru OBMJ       4
VII OBM                                        4
XXX OBM                                        4
Primul baraj de selecție pentru OBMJ           2
XXVII OBM                                      1
Name: count, dtype: int64

In [52]:
df[df['banca']=='XXIV OBM']

,id,enunciado,solucao_markdown,imagens,pais,banca,topico,idioma,tipo_problema,gabarito,ano_extraido,ano,enunciado_sem_latex,idioma_final,origem_idioma,idioma_limpo
374,02gm,A finite collection of squares has total area ...,[Let the sides of the squares be equal to $a_i...,[],Brazil,XXIV OBM,[Geometry > Plane Geometry > Miscellaneous > C...,en,proof only,NaN,NaN,2002,Afinitecollectionofsquareshastotalarea.Showtha...,English,dataset,en
4253,02gl,"For any non-empty subset $A$ of $\{1, 2, \dots...",[Let $m$ and $M$ be the sum of the minima and ...,[],Brazil,XXIV OBM,[Discrete Mathematics > Combinatorics > Counti...,en,proof and answer,(n - 3) * 2^n + n + 3,NaN,2002,Foranynon-emptysubsetofdefineasthelargesteleme...,English,dataset,en
5456,02gi,Show that there is a set of $2002$ distinct po...,"[Let $p$ be a prime and $A = \{p, 2p, 3p, \dot...",[],Brazil,XXIV OBM,[Number Theory > Divisibility / Factorization ...,en,proof only,NaN,2002,2002,Showthatthereisasetofdistinctpositiveintegerss...,English,dataset,en
9884,02gn,Show that we cannot form more than $4096$ bina...,"[Let $p$, $q$ be two binary sequences. Define ...",[],Brazil,XXIV OBM,[Discrete Mathematics > Combinatorics > Counti...,en,proof only,NaN,NaN,2002,Showthatwecannotformmorethanbinarysequencesofl...,English,dataset,en
12250,02gj,$ABCD$ is a cyclic quadrilateral and $M$ a poi...,[![](attached_image_1.png)\n\nSince the perime...,[{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIH...,Brazil,XXIV OBM,[Geometry > Plane Geometry > Quadrilaterals > ...,en,proof only,NaN,NaN,2002,isacyclicquadrilateralandapointonthesidesuchth...,English,dataset,en
22004,02gk,The squares of an $m \times n$ board are label...,[Consider the center of the $mn$ unit squares ...,[{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIH...,Brazil,XXIV OBM,[Discrete Mathematics > Combinatorics > Counti...,en,proof only,NaN,NaN,2002,Thesquaresofanboardarelabeledfromtosothatthesq...,English,dataset,en

In [43]:
ROMANO_PARA_ANO_OBM = {
    "I": 1979, "II": 1980, "III": 1981, "IV": 1982, "V": 1983,
    "VI": 1984, "VII": 1985, "VIII": 1986, "IX": 1987, "X": 1988,
    "XI": 1989, "XII": 1990, "XIII": 1991, "XIV": 1992, "XV": 1993,
    "XVI": 1994, "XVII": 1995, "XVIII": 1996, "XIX": 1997, "XX": 1998,
    "XXI": 1999, "XXII": 2000, "XXIII": 2001, "XXIV": 2002, "XXV": 2003,
    "XXVI": 2004, "XXVII": 2005, "XXVIII": 2006, "XXIX": 2007, "XXX": 2008,
    "XXXI": 2009, "XXXII": 2010, "XXXIII": 2011, "XXXIV": 2012, "XXXV": 2013,
    "XXXVI": 2014, "XXXVII": 2015, "XXXVIII": 2016, "XXXIX": 2017, "XL": 2018
}


# Pega o número romano antes de OBM (ex: "XXIV OBM", "XXXI Brazilian Math Olympiad")
regex_romano = r"\b([IVXLCDM]+)\s*(?:OBM|Brazilian Math Olympiad)\b"

# Extrai apenas a letra romana (ex: "XXIV", "III", "XXXI")
edicao_romana = df["banca"].str.extract(regex_romano, flags=re.IGNORECASE)[0]

In [44]:
# Mapeia apenas as letras romanas capturadas
ano_pelo_romano = edicao_romana.map(ROMANO_PARA_ANO_OBM)

# Preenche os anos vazios
df["ano"] = df["ano"].fillna(ano_pelo_romano)

In [51]:
# 1. Garante que qualquer texto vire número (e o que falhar vira NaN)
df["ano"] = pd.to_numeric(df["ano"], errors="coerce")
# 2. Converte para o tipo inteiro com suporte a nulo (Int64 com 'I' maiúsculo)
df["ano"] = df["ano"].astype("Int64")

In [ ]:
df['ano']

In [53]:
# Mostra linhas onde as duas colunas têm valores diferentes (se houver)
conflitos = df[df["ano"].notna() & df["ano_extraido"].notna() & (df["ano"] != df["ano_extraido"])]
print(f"Total de conflitos entre 'ano' e 'ano_extraido': {len(conflitos)}")

if len(conflitos) > 0:
    display(conflitos[["id", "banca", "ano", "ano_extraido"]].head(5))

Total de conflitos entre 'ano' e 'ano_extraido': 6071

      id                                              banca   ano ano_extraido
3   00rl                              BMO  Short List Final  2016         2016
4   00xp                                         Baltic Way  1993         1993
17  064l  Auswahlwettbewerb zur Internationalen Mathemat...  2022         2022
19  06j5                                         IMO HK TST  1997         1997
20  06op                          IMO  Shortlisted Problems  2006         2006